# Generated by Django 4.0.4 on 2022-06-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contacto_registro_remove_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='usuario',
            new_name='nombre',
        ),
    ]
