# Generated by Django 4.0.4 on 2022-06-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_usuario_registro_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='ciudad',
        ),
    ]
